### ISSUE TITLE
不支持打开加密word

### ISSUE THREAD

**Issue by lihejia** [501351981/vue-office#104]
不支持打开加密word，选择加密过的word，会提示以下错误：
出差 Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
    at m.readEndOfCentral (docx-40967bb8.js:12:32249)
    at m.load (docx-40967bb8.js:12:33897)
    at docx-40967bb8.js:12:5347
    at async i.load (docx-40967bb8.js:82:367)
    at async l.load (docx-40967bb8.js:96:13893)
    at async e.renderAsync (docx-40967bb8.js:82:36237)

运行环境：mac chrome ,
在线演示demo

**Comment by 501351981** [comment]
底层为docx-preview库，暂不支持
