### ISSUE TITLE
二进制文件 预览xlsx类型文件报错 其他类型文件使用二进制预览正常

### ISSUE THREAD

**Issue by guaobai** [501351981/vue-office#166]
报错信息
TypeError: Cannot read properties of null (reading 'childNodes')
    at m.element (index.js:96:1)
    at e.DocumentParser.parseDocumentFile (index.js:82:1)
    at m.parseXml (index.js:82:1)
    at m.eval (index.js:82:1)
    at Generator.next (<anonymous>)
    at ke (index.js:1:1)

**Comment by guaobai** [comment]
没注意看文档 我把xlsx的文件放到doc去展示了 用excel的就行了

**Comment by guaobai** [comment]
咱就是说 再来个打印功能就完美了 期待
