### ISSUE TITLE
部分.docx文档无法预览

### ISSUE THREAD

**Issue by AnnCY1** [501351981/vue-office#200]
error事件报错信息如下：

```
TypeError: Cannot read properties of null (reading 'localName')
    at index-5e7d05b0.js:82:11302
    at x.foreach (index-5e7d05b0.js:82:24348)
    at e.DocumentParser.parseRun (index-5e7d05b0.js:82:11247)
    at e.DocumentParser.parseParagraph (index-5e7d05b0.js:82:9929)
    at e.DocumentParser.parseBodyElements (index-5e7d05b0.js:82:5151)
    at e.DocumentParser.parseDocumentFile (index-5e7d05b0.js:82:4842)
    at m.parseXml (index-5e7d05b0.js:82:31328)
    at m.<anonymous> (index-5e7d05b0.js:82:1386)
    at Generator.next (<anonymous>)
    at P (index-5e7d05b0.js:1:2091)
```

无法正常预览的文件：
[通知.docx](https://github.com/501351981/vue-office/files/13737025/default.docx)
[通知（第二人称）.docx](https://github.com/501351981/vue-office/files/13737024/default.docx)
[公文版式-版记.docx](https://github.com/501351981/vue-office/files/13737023/-.docx)

**Comment by lexmin0412** [comment]
Same Problem.
