### ISSUE TITLE
导入运行报错 Uncaught TypeError: isFunction is not a function at defineComponent (runtime-core.esm-bundler.js:2316:10)  at activity.tsx:12:16

### ISSUE THREAD

**Issue by 879291903** [501351981/vue-office#264]
组件名称及版本： @vue-office/pdf 1.6.5
运行环境：
浏览器：谷歌浏览器
vue版本：vue 3.3.8
打包工具及版本：vite 5.2.8
问题描述：报错
Uncaught TypeError: isFunction is not a function at defineComponent (runtime-core.esm-bundler.js:2316:10)  at activity.tsx:12:16

**Comment by raohuiyong** [comment]
我也是这个问题？有解决方案吗

**Comment by lgw42032** [comment]
同求解决方案

**Comment by LRLHHC** [comment]
main.js 里面把 import { createApp } from 'vue' 放第一行就不报错了，我是这样的

**Comment by lglglglglg** [comment]
我今天也遇到了这个问题。搞了快一个小时了。官网ai谷歌搜遍了。最后来到这里看了一下。看到楼上 说  把createApp 放在最上面
`import { createApp } from 'vue';
import TDesign from 'tdesign-vue-next';`
试了一下 恢复正常了。但是具体不知道根本原因。
