### ISSUE TITLE
使用非Vue框架预览失败

### ISSUE THREAD

**Issue by Iamdog** [501351981/vue-office#338]
预览失败 TypeError: n.item.url.replace is not a function
    at Proxy.<anonymous> (chunk-vendors.js:35455:114)
    at pages-fileyl-fileyl.js:1027:491762
    at new Promise (<anonymous>)
    at pages-fileyl-fileyl.js:1027:491707
    at xg (pages-fileyl-fileyl.js:1027:492083)
    at pages-fileyl-fileyl.js:1027:506225
    at new Promise (<anonymous>)
    at Pg.preview (pages-fileyl-fileyl.js:1027:506199)
    at eval (fileyl.vue:23:1)

**Comment by 501351981** [comment]
有问题换纯js方式预览吧
