### ISSUE TITLE
Cannot read properties of null (reading 'clientWidth')

### ISSUE THREAD

**Issue by noob-Jp** [501351981/vue-office#50]
使用vue-office-excel时，放大缩小浏览器大小的时候会出现报错。
我把vue-office-excel放到了一个dialog里面（使用的element-ui库）
当第一次进入到dialog后操作浏览器大小不会出现这个问题，当关闭dialog后再次进入后操作浏览器就会出现报错。
完整的报错信息如下：
`ERROR
Cannot read properties of null (reading 'clientWidth')
TypeError: Cannot read properties of null (reading 'clientWidth')
    at Object.width (webpack-internal:///./node_modules/@vue-office/excel/lib/index.js:35:91164)
    at sh.viewWidth (webpack-internal:///./node_modules/@vue-office/excel/lib/index.js:5:51875)
    at rp.getRect (webpack-internal:///./node_modules/@vue-office/excel/lib/index.js:5:148700)
    at rp.getTableOffset (webpack-internal:///./node_modules/@vue-office/excel/lib/index.js:5:148872)
    at rp.sn (webpack-internal:///./node_modules/@vue-office/excel/lib/index.js:5:138407)
    at rp.reload (webpack-internal:///./node_modules/@vue-office/excel/lib/index.js:5:148610)
    at eval (webpack-internal:///./node_modules/@vue-office/excel/lib/index.js:5:144665)`
package.json信息如下
` "dependencies": {
    "@vue-office/docx": "^1.1.3",
    "@vue-office/excel": "^1.1.3",
    "@vue/composition-api": "^1.7.1",
    "axios": "^0.24.0",
    "core-js": "^3.6.5",
    "element-ui": "^2.15.13",
    "fake-progress": "^1.0.4",
    "less": "^4.1.3",
    "less-loader": "^11.1.0",
    "luckyexcel": "^1.0.1",
    "mockjs": "^1.1.0",
    "node-polyfill-webpack-plugin": "^2.0.1",
    "nprogress": "^0.2.0",
    "sass": "^1.62.0",
    "sass-loader": "^13.2.2",
    "tui-image-editor": "^3.15.3",
    "vue": "^2.7.14",
    "vue-contextmenu": "^1.5.11",
    "vue-demi": "^0.13.11",
    "vue-page-split": "^2.0.1",
    "vuedraggable": "^2.24.3",
    "vuex": "^3.6.2"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "babel-eslint": "^10.1.0",
    "babel-polyfill": "^6.26.0",
    "eslint": "^7.32.0",
    "eslint-plugin-vue": "^8.0.3"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },`

**Comment by 501351981** [comment]
试试这个版本，@vue-office/excel@1.1.4
